newTextBox("$%&$%&!!!",c_green,spr_thumb_turtle);
newTextBox("Cosa è successo, nipote?",c_olive,spr_thumb_grandfather);
newTextBox("I miei amici conigli sono andati tutti a giocare giù in paese..",c_green,spr_thumb_turtle);
newTextBox("E..",c_olive,spr_thumb_grandfather);
newTextBox("E volevo andare con loro, ma questo grosso fardello mi impedisce di saltare!",c_green,spr_thumb_turtle);
newTextBox("... quale fardello?",c_olive,spr_thumb_grandfather);
newTextBox("Il guscio, no? E' grosso, pesante e inutile!",c_green,spr_thumb_turtle);
newTextBox("Come vorrei non averlo..",c_green,spr_thumb_turtle);
newTextBox("Ma sei una tartaruga, è parte di te!",c_olive,spr_thumb_grandfather);
newTextBox("Lo so nonno.. è solo che a volte non vorrei proprio esserlo..",c_green,spr_thumb_turtle);
newTextBox("Nipote..",c_olive,spr_thumb_grandfather);
newTextBox("Lo so..",c_green,spr_thumb_turtle);
newTextBox("Ma parliamo di cose allegre.. cosa regali a nonna per il compleanno?",c_olive,spr_thumb_grandfather);
newTextBox("Aaaa! Mi ero proprio scordato!! Hai dei suggerimenti?",c_green,spr_thumb_turtle);
newTextBox("Perchè non le prepari il suo dolce preferito?",c_olive,spr_thumb_grandfather);
newTextBox("I babbà?",c_green,spr_thumb_turtle);
newTextBox("Ma quali babbà, i tartascotti!",c_olive,spr_thumb_grandfather);
newTextBox("Tartascotti? Ma non saprei da dove cominciare..",c_green,spr_thumb_turtle);
newTextBox("Ti aiuto io, ho una ricetta fantastica!",c_olive,spr_thumb_grandfather);
newTextBox("Corri giù in paese a prendere  la farina!",c_olive,spr_thumb_grandfather);
newTextBox("Ma questa volta non seguire i conigli, prendi la scorciatoia dietro casa",c_olive,spr_thumb_grandfather);
newTextBox("Scorciatoia??",c_green,spr_thumb_turtle);

can_escape = true;